{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-webmvc",
    "version": "6.1.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.12"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.12"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.12"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.12"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.1.12"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.12"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-6.1.12.jar",
          "url": "spring-webmvc-6.1.12.jar",
          "size": 1046956,
          "sha512": "22a2c5a4a0240151057dce62ce418456463de95b18530294c3cb9c8817b19fc97c90d63f625cf46839d059b401e62a4f9034cdd0d2dda72e85d27f2a3f99a8b1",
          "sha256": "85d594b40a4c53745cbb21547307128cb7cf3926b8e55daeafc7a2cae09e7b79",
          "sha1": "86bb0c203d68adb4b2675765f5a372f4c5254b2d",
          "md5": "08172daa5f2e9a89daa15ca99bb2582c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.12"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.12"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.12"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.12"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.1.12"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.12"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-6.1.12.jar",
          "url": "spring-webmvc-6.1.12.jar",
          "size": 1046956,
          "sha512": "22a2c5a4a0240151057dce62ce418456463de95b18530294c3cb9c8817b19fc97c90d63f625cf46839d059b401e62a4f9034cdd0d2dda72e85d27f2a3f99a8b1",
          "sha256": "85d594b40a4c53745cbb21547307128cb7cf3926b8e55daeafc7a2cae09e7b79",
          "sha1": "86bb0c203d68adb4b2675765f5a372f4c5254b2d",
          "md5": "08172daa5f2e9a89daa15ca99bb2582c"
        }
      ]
    }
  ]
}
