{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-aop",
    "version": "3.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.12"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.22.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-aop-3.3.3.jar",
          "url": "spring-boot-starter-aop-3.3.3.jar",
          "size": 4766,
          "sha512": "1f0b3e05b696f925dc75543821ef6e37ad496e844baff49a8c7de80074c030e932fa89c7ddc409e05af2c3148ff48625016543ddf5154b9361bd547ef18dd55b",
          "sha256": "53f2c4f764a59c0f93310cb3ab6499888d725abf863f1a197bb9cacbc659fc3b",
          "sha1": "f64c22484c1ab36ae70abc752509ec4c7b1abcfc",
          "md5": "1e0e67ab241f20b339f17cf86d117539"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.12"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.22.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-aop-3.3.3.jar",
          "url": "spring-boot-starter-aop-3.3.3.jar",
          "size": 4766,
          "sha512": "1f0b3e05b696f925dc75543821ef6e37ad496e844baff49a8c7de80074c030e932fa89c7ddc409e05af2c3148ff48625016543ddf5154b9361bd547ef18dd55b",
          "sha256": "53f2c4f764a59c0f93310cb3ab6499888d725abf863f1a197bb9cacbc659fc3b",
          "sha1": "f64c22484c1ab36ae70abc752509ec4c7b1abcfc",
          "md5": "1e0e67ab241f20b339f17cf86d117539"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-aop-3.3.3-javadoc.jar",
          "url": "spring-boot-starter-aop-3.3.3-javadoc.jar",
          "size": 4739,
          "sha512": "031a0568c4878b206235665dbd6b15aff53cd11a6ee57f894d31f1a05aeed7d5a1c5e0ee3f9a6848ab7723d37cb6833f1fddd2e0941ec0a67a292f9098081453",
          "sha256": "07a0c59b73cbd523335cf4f9a084b11cbed48ac2ccb2a65da0de07c195752d52",
          "sha1": "f42d627f56c8ad7fd2f5ff904290cb7c71821db7",
          "md5": "94c374321ac30050b3c6ff7be12db3b6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-aop-3.3.3-sources.jar",
          "url": "spring-boot-starter-aop-3.3.3-sources.jar",
          "size": 4738,
          "sha512": "3328d89545e46214a0a8225e5315d372d3739d6424489eabdd137fc0a94850b4e29035c4bc58120d7d4c8945ec2f50777503dfaa1c505c31f67a0b7b496a99a9",
          "sha256": "1332c9a6d1f5d6028e7d5ff6dbef9ab32983a987a2e8769551ffc246ab869d32",
          "sha1": "114fd5d4802448b47a4df90ce86f87ce17548589",
          "md5": "5b84911bcfd537b0c79ad2a22bacb997"
        }
      ]
    }
  ]
}
